apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-ingress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/yoav-yung/argocd-repo-for-tests/helm-charts'
    chart: argocd-ingress
    targetRevision: "0.1.0"
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd-ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
